### PR TITLE
Create Apache 2.0 License for developer.makerdao.com

### PR DESCRIPTION
**Pull request by CPSTL**

### CODE REVIEW

**Comment by zack-eth** [comment]
We can omit the Apache header and begin with the Copyright (line 5).

**Comment by zack-eth** [comment]
Let's keep it "MakerDAO" (as opposed to "Maker Foundation"), until further notice.

**Comment by zack-eth** [comment]
We also need to reference licenses to 3rd party projects on which this particular repo depends (e.g. https://github.com/makerdao/testchain-dockerservice/blob/master/LICENSE).  Because this will take a moderate amount of effort, I am confirming that this is strictly required...

**Comment by zack-eth** [comment]
"http://www.apache.org/licenses/LICENSE-2.0" is typically indented (see https://www.apache.org/licenses/LICENSE-2.0.html).  But now I'm just being pedantic ;)

**Comment by zdumitru** [comment]
@zskolnik Can this be merged now?

**Comment by zack-eth** [comment]
> @zskolnik Can this be merged now?

@zdumitru We still need to update https://github.com/makerdao/developer.makerdao.com/blob/add-license/LICENSE#L1

**Review by zack-eth — APPROVED** [review]
lgtm

**Pull request merged**
